version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_DATABASE=ride_sharing
      - MARIADB_HOSTNAME=db
      - MARIADB_PASSWORD=fpofwapjia채pjw채82qioaj채pdoa채
      - MARIADB_ROOT_PASSWORD=dwokpojfwaPIJWfoij209qo9pa
      - MARIADB_USER=ride_sharing
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
