version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: dockerfile
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
