version: '3.8'

services:
  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: ["./backend/main"]
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
