# Verwende ein Go-Image, um die Anwendung zu bauen
FROM 1.23.2 AS builder

# Setze das Arbeitsverzeichnis
WORKDIR /usr/src/app

# Kopiere die Go-Module-Dateien und lade alle Abhängigkeiten
COPY go.mod go.sum ./
RUN go mod download

# Kopiere den Rest des Anwendungsquellcodes
COPY . .

# Baue die Anwendung
RUN go build -o main

# Verwende ein schlankes Image, um die Anwendung auszuführen
FROM alpine:latest

WORKDIR /root/

# Kopiere die gebaute Go-Anwendung aus der vorherigen Stage
COPY --from=builder /usr/src/app/main .

# Setze den Standardbefehl
CMD ["./main"]
