# Setze das Arbeitsverzeichnis
WORKDIR /usr/src/app

# Kopiere die Go-Module-Dateien und lade alle Abhängigkeiten
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Kopiere den Rest des Anwendungsquellcodes
COPY backend/ .

# Baue die Anwendung
RUN go build -o main

# Verwende ein schlankes Image, um die Anwendung auszuführen
FROM alpine:latest

WORKDIR /root/

# Kopiere die gebaute Go-Anwendung aus der vorherigen Stage
COPY --from=builder /usr/src/app/main .

# Setze den Standardbefehl
CMD ["./main"]